### ISSUE TITLE
支持多用户系统

### ISSUE THREAD

**Issue by emclab** [Eric-Guo/wechat#106]
我们需要把微信整合进一个多用户的系统（所有用户共享一个URL），允许每个用户有自己的微信号，这样每个 用户可以根据自己的需要给自己的好友（圈）微信来往。我们在使用API时应该调整什么？API同时支持多用户吗？谢谢。

**Comment by Eric-Guo** [comment]
在controller里使用wechat_api或者wechat_responder时需要显式声明微信公众号的参数，而不是使用yml配置。
另外要避免直接呼叫Wechat.api，而是在controller中使用wechat方法。
目前wechat
gem完整支持controller级别的多账号，但是我不确定你是否打算在完全相同的URL里面(同一个controller中)支持多个公众号，如果是这样，不说腾讯微信后台允许不允许，至少从Rails这边，目前是无法区分一个请求是来自于哪个公众号的。
On Apr 28, 2016 2:20 AM, "emclab" <notifications@github.com> wrote:

我们需要把微信整合进一个多用户的系统（所有用户共享一个URL），允许每个用户有自己的微信号，这样每个
用户可以根据自己的需要给自己的好友（圈）微信来往。我们在使用API时应该调整什么？API同时支持多用户吗？谢谢。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/Eric-Guo/wechat/issues/106>

**Comment by emclab** [comment]
一个公司有多个用户，每个用户都有自己的微信号。在这种情况下，wechat gem允许各个用户用自己的微信号发信吗？Thanks.

**Comment by Eric-Guo** [comment]
允许，但是需要在controller中配置，不能通过命令行方式。

**Comment by emclab** [comment]
能推荐几个开源样版系统参考吗？我对微信的RAILS接口不熟。有帮助就好。谢谢！

**Comment by Eric-Guo** [comment]
[wechat-starter](https://github.com/goofansu/wechat-starter)就很好啊，支付，oauth2，wechat集成，该演示的都演示了。
